[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[functions]
  external_node_modules = ["express", "sequelize", "cors", "pg-hstore", "pg"]
  node_bundler = "esbuild"